apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d57ojr6vl-python 
  janus-idp.io/tekton: d57ojr6vl-python
  backstage.io/kubernetes-id: d57ojr6vl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d57ojr6vl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml