apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: d57ojr6vl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b64ab3681c.gikd.p3.openshiftapps.com/rhtap/rhtap-qe:453cf4ffc7feb21cd5d328584c54419b6321dd1c@sha256:af88fbf96066dc6c404dc6abdcdf7b15566191a9b8dba1294a3ac908514fcdc1
          name: container-image
