apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d57ojr6vl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d57ojr6vl-python 
  name: d57ojr6vl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d57ojr6vl-python 
